micronaut:
  server:
    port: 8080
  application:
    name: feedback

endpoints:
  health:
    enabled: true
    sensitive: false
    url:
      enabled: true

cassandra:
  default:
    basic:
      contact-points:
        - "127.0.0.1:9042"
      session-keyspace: feedbackkeyspace
      load-balancing-policy:
        local-datacenter: datacenter1

nats:
  addresses: ${nats_host:localhost}
  username: ${nats_username:guest}
  password: ${nats_password:guest}